In [1]:
import pandas as pd
data=pd.read_csv("Social_Network_Ads.csv")
data

      User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [2]:
data=pd.get_dummies(data,drop_first=True).astype(int)
data

      User ID  Age  EstimatedSalary  Purchased  Gender_Male
0    15624510   19            19000          0            1
1    15810944   35            20000          0            1
2    15668575   26            43000          0            0
3    15603246   27            57000          0            0
4    15804002   19            76000          0            1
..        ...  ...              ...        ...          ...
395  15691863   46            41000          1            0
396  15706071   51            23000          1            1
397  15654296   50            20000          1            0
398  15755018   36            33000          0            1
399  15594041   49            36000          1            0

[400 rows x 5 columns]

In [3]:
independent=data[['Age', 'EstimatedSalary', 'Gender_Male']]
dependent=data[['Purchased']]

In [4]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(independent,dependent,test_size=1/3,random_state=0)

In [6]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

In [8]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import GridSearchCV
param_grid={'solver':['lbfgs','newton-cg','liblinear','saga'],'penalty':['l2']}
grid=GridSearchCV
grid=GridSearchCV(LogisticRegression(),param_grid,refit=True,verbose=3,n_jobs=-1,cv=5)
grid.fit(x_train,y_train)

Fitting 5 folds for each of 4 candidates, totalling 20 fits

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

GridSearchCV(cv=5, estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'penalty': ['l2'],
                         'solver': ['lbfgs', 'newton-cg', 'liblinear', 'saga']},
             verbose=3)

In [12]:
re=grid.cv_results_
grid_predictions=grid.predict(x_test)
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,grid_predictions)
from sklearn.metrics import classification_report
clf_report=classification_report(y_test,grid_predictions)

In [14]:
print(cm)

[[79  6]
 [10 39]]

In [16]:
print(clf_report)

              precision    recall  f1-score   support

           0       0.89      0.93      0.91        85
           1       0.87      0.80      0.83        49

    accuracy                           0.88       134
   macro avg       0.88      0.86      0.87       134
weighted avg       0.88      0.88      0.88       134

In [18]:
from sklearn.metrics import roc_auc_score
roc_auc_score(y_test,grid.predict_proba(x_test)[:,1])

np.float64(0.9507803121248499)

In [19]:
table=pd.DataFrame.from_dict(re)
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_penalty,param_solver,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.032434,0.012047,0.018412,0.004786,l2,lbfgs,"{'penalty': 'l2', 'solver': 'lbfgs'}",0.814815,0.811321,0.698113,0.924528,0.924528,0.834661,0.084541,1
1,0.015175,0.004479,0.015455,0.005261,l2,newton-cg,"{'penalty': 'l2', 'solver': 'newton-cg'}",0.814815,0.811321,0.698113,0.924528,0.924528,0.834661,0.084541,1
2,0.010544,0.001321,0.010520,0.001122,l2,liblinear,"{'penalty': 'l2', 'solver': 'liblinear'}",0.814815,0.811321,0.698113,0.924528,0.924528,0.834661,0.084541,1
3,0.008091,0.003252,0.005958,0.001350,l2,saga,"{'penalty': 'l2', 'solver': 'saga'}",0.814815,0.811321,0.698113,0.924528,0.924528,0.834661,0.084541,1